version: '3'

services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: index_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/var/www:ro
      - ./log/nginx:/var/log/nginx
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    environment: 
      - TZ=Asia/Shanghai
